### ISSUE TITLE
Why type == 'stderr'  and event == undefined ?   async/await

### ISSUE THREAD

**Issue by GSangQin** [yandex/mocha-parallel-tests#142] opened 2018-05-22 03:18 UTC
{ execTime: 63554,
  file: 'app.js',
  output: 
   [ { data: {}, event: 'start', type: 'runner' },
     { data: [Object], event: 'suite', type: 'runner' },
     { data: [Object], event: 'suite', type: 'runner' },
     { data: [Object], event: 'hook', type: 'runner' },
     { data: [Object], event: 'hook end', type: 'runner' },
     { data: [Object], event: 'test', type: 'runner' },
     { data: [Object], event: 'hook', type: 'runner' },
     { data: [Object], event: 'hook end', type: 'runner' },
     { data: [Object], event: 'pass', type: 'runner' },
     { data: [Object], event: 'test end', type: 'runner' },
     { data: [Object], event: 'hook', type: 'runner' },
     { data: [Object], event: 'hook end', type: 'runner' },
     { data: [Object], event: 'test', type: 'runner' },
     { data: [Object], event: 'hook', type: 'runner' },
     { data: [Object], event: 'hook end', type: 'runner' },
     { data: [Object], event: 'pass', type: 'runner' },
     { data: [Object], event: 'test end', type: 'runner' },
     { data: [Object], event: 'hook', type: 'runner' },
     { data: [Object], event: 'hook end', type: 'runner' },
     { data: [Object], event: 'hook', type: 'runner' },
     { data: [Object], event: 'hook end', type: 'runner' },
     { data: [Object], event: 'suite end', type: 'runner' },
     { data: [Object], event: 'suite end', type: 'runner' },
     { data: [Object], event: 'fail', type: 'runner' },
     { data: <Buffer 2f 55 73 65 72 73 2f 61 6c 69 62 61 62 61 2f 77 6f 72 6b 73 70 61 63 65 2f 6d 61 63 61 63 61 2d 70 61 67 65 63 68 65 63 6b 2f 6e 6f 64 65 5f 6d 6f 64 ... >,
       event: undefined,
       type: 'stderr' } ] }
(node:16306) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Subprocess app.js{undefined} didn't send an "end" message
    at MochaWrapper.findRootData (/Users/alibaba/workspace/macaca-pagecheck/node_modules/_mocha-parallel-tests@2.0.0-alpha.3@mocha-parallel-tests/dist/main/mocha.js:87:9)
    at MochaWrapper.addSubprocessSuites (/Users/alibaba/workspace/macaca-pagecheck/node_modules/_mocha-parallel-tests@2.0.0-alpha.3@mocha-parallel-tests/dist/main/mocha.js:93:33)
    at taskManager.run.then (/Users/alibaba/workspace/macaca-pagecheck/node_modules/_mocha-parallel-tests@2.0.0-alpha.3@mocha-parallel-tests/dist/main/mocha.js:67:22)
    at <anonymous>
(node:16306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16306) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 1999** [comment] 2018-05-22 04:51
@GSangQin can you provide an example how to reproduce the error?

**Comment by 1999** [comment] 2018-05-31 11:43
The problem is probably related to subprocess crashing before sending an "end" message. This is fixed in mocha-parallel-tests@2.0.1

**Closed by 1999** 2018-05-31 11:43 UTC
Labels: v2
